modLoader = "javafml"
loaderVersion = "[45,)"
license = "LGPLv3"

[[mods]]
modId = "bosomlang"
version = "${version}"
displayName = "BosomLang Mod"
authors = "wdog5"
description = '''
A mod that localizes hardcoded info, supports Forge and Fabric
'''

[[dependencies.bosomlang]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bosomlang]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.2)"
ordering = "NONE"
side = "BOTH"